# Generated by Django 5.0.7 on 2024-11-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistoryReport',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='历史报告编号')),
                ('zero_to_25000_mater', models.CharField(max_length=255, verbose_name='0-25000原材料')),
                ('zero_to_25000_att', models.CharField(max_length=255, verbose_name='0-25000附件')),
                ('two_fifty_one_to_45000_mater', models.CharField(max_length=255, verbose_name='25001-45000原材料')),
                ('two_fifty_one_to_45000_att', models.CharField(max_length=255, verbose_name='25001-45000附件')),
                ('four_fifty_one_to_70000_mater', models.CharField(max_length=255, verbose_name='45001-70000原材料')),
                ('four_fifty_one_to_70000_att', models.CharField(max_length=255, verbose_name='45001-70000附件')),
                ('seven_zero_zero_one_mater', models.CharField(max_length=255, verbose_name='70001及以上原材料')),
                ('seven_zero_zero_one_att', models.CharField(max_length=255, verbose_name='70001及以上附件')),
                ('management', models.CharField(max_length=255, verbose_name='管理费用')),
                ('sales', models.CharField(max_length=255, verbose_name='销售费用')),
                ('purchase', models.CharField(max_length=255, verbose_name='采购费用')),
                ('prd', models.CharField(max_length=255, verbose_name='生产费用')),
                ('rnd', models.CharField(max_length=255, verbose_name='研发费用')),
                ('register', models.CharField(max_length=255, verbose_name='注册费用')),
                ('reserve', models.CharField(max_length=255, verbose_name='储备费用')),
                ('loan', models.CharField(max_length=255, verbose_name='贷款费用')),
                ('total', models.CharField(max_length=255, verbose_name='总费用')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cycle', verbose_name='周期编号')),
            ],
        ),
    ]
