# Generated by Django 5.0.7 on 2025-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='term_long',
        ),
        migrations.AddField(
            model_name='term',
            name='term_emph',
            field=models.CharField(default='', max_length=255, verbose_name='强调'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_equation',
            field=models.CharField(default='', max_length=255, verbose_name='公式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_list',
            field=models.CharField(default='', max_length=255, verbose_name='列表'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_tabledata',
            field=models.TextField(default='', verbose_name='表数据'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_tablehead',
            field=models.TextField(default='', verbose_name='表头'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_tablename',
            field=models.TextField(default='', verbose_name='表格名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_txt1',
            field=models.TextField(default='', verbose_name='文本一'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term_txt2',
            field=models.TextField(default='', verbose_name='文本二'),
            preserve_default=False,
        ),
    ]
