# Generated by Django 5.0.7 on 2025-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_term_term_long_term_term_emph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_emph',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='强调'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_equation',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='公式'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_list',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='列表'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_tabledata',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表数据'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_tablehead',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表头'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_tablename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表格名称'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_txt1',
            field=models.TextField(blank=True, null=True, verbose_name='文本一'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_txt2',
            field=models.TextField(blank=True, null=True, verbose_name='文本二'),
        ),
    ]
