# Generated by Django 5.0.7 on 2024-11-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_markethistoryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('competition_id', models.AutoField(primary_key=True, serialize=False, verbose_name='竞争表编号')),
                ('company_market_price', models.CharField(max_length=255, verbose_name='本企业一般市场价格')),
                ('competitor_market_price', models.CharField(max_length=255, verbose_name='计算机一般市场价格')),
                ('company_ad_expenses', models.CharField(max_length=255, verbose_name='本企业广告费用投入')),
                ('competitor_ad_expenses', models.CharField(max_length=255, verbose_name='计算机广告费用投入')),
                ('company_sales_staff', models.CharField(max_length=255, verbose_name='本企业销售人员数量')),
                ('competitor_sales_staff', models.CharField(max_length=255, verbose_name='计算机销售人员数量')),
                ('company_quality_rating', models.CharField(max_length=255, verbose_name='本企业产品质量评价')),
                ('competitor_quality_rating', models.CharField(max_length=255, verbose_name='计算机产品质量评价')),
                ('company_market_sales_volume', models.CharField(max_length=255, verbose_name='本企业一般市场销售量')),
                ('competitor_market_sales_volume', models.CharField(max_length=255, verbose_name='计算机一般市场销售量')),
                ('company_market_sales_revenue', models.CharField(max_length=255, verbose_name='本企业一般市场销售额')),
                ('competitor_market_sales_revenue', models.CharField(max_length=255, verbose_name='计算机一般市场销售额')),
                ('company_theoretical_share', models.CharField(max_length=255, verbose_name='本企业理论市场占有率')),
                ('competitor_theoretical_share', models.CharField(max_length=255, verbose_name='计算机理论市场占有率')),
                ('company_actual_share', models.CharField(max_length=255, verbose_name='本企业实际市场占有率')),
                ('competitor_actual_share', models.CharField(max_length=255, verbose_name='计算机实际市场占有率')),
                ('company_extra1_sales_volume', models.CharField(max_length=255, verbose_name='本企业附加市场Ⅰ销售量')),
                ('competitor_extra1_sales_volume', models.CharField(max_length=255, verbose_name='计算机附加市场Ⅰ销售量')),
                ('company_extra1_sales_revenue', models.CharField(max_length=255, verbose_name='本企业附加市场Ⅰ销售额')),
                ('competitor_extra1_sales_revenue', models.CharField(max_length=255, verbose_name='计算机附加市场Ⅰ销售额')),
                ('company_extra2_sales_volume', models.CharField(max_length=255, verbose_name='本企业附加市场Ⅱ销售量')),
                ('competitor_extra2_sales_volume', models.CharField(max_length=255, verbose_name='计算机附加市场Ⅱ销售量')),
                ('company_extra2_sales_revenue', models.CharField(max_length=255, verbose_name='本企业附加市场Ⅱ销售额')),
                ('competitor_extra2_sales_revenue', models.CharField(max_length=255, verbose_name='计算机附加市场Ⅱ销售额')),
                ('company_winning_company', models.CharField(max_length=255, verbose_name='本企业中标企业')),
                ('competitor_winning_company', models.CharField(max_length=255, verbose_name='计算机中标企业')),
                ('company_bid_price', models.CharField(max_length=255, verbose_name='本企业中标企业投标价格')),
                ('competitor_bid_price', models.CharField(max_length=255, verbose_name='计算机中标企业投标价格')),
                ('company_inventory', models.CharField(max_length=255, verbose_name='本企业产品累积库存数量')),
                ('competitor_inventory', models.CharField(max_length=255, verbose_name='计算机产品累积库存数量')),
                ('company_capacity', models.CharField(max_length=255, verbose_name='本企业生产线生产能力')),
                ('competitor_capacity', models.CharField(max_length=255, verbose_name='计算机生产线生产能力')),
                ('company_profit', models.CharField(max_length=255, verbose_name='本企业税前经营成果')),
                ('competitor_profit', models.CharField(max_length=255, verbose_name='计算机税前经营成果')),
                ('company_assets_liabilities', models.CharField(max_length=255, verbose_name='本企业资产负债总和')),
                ('competitor_assets_liabilities', models.CharField(max_length=255, verbose_name='计算机资产负债总和')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cycle', verbose_name='周期编号')),
            ],
        ),
    ]
