# Generated by Django 5.0.7 on 2024-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_competitionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='competition_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='竞争表标题'),
        ),
    ]
