# Generated by Django 5.0.7 on 2024-11-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_company_value_period_1_financialindicator_period_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_6',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='period_7',
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='RD_investment_effect',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='研发投入效应'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='actual_market_share',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='实际市场占有率'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='advertising_cost',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='广告费用'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='market_plan_quantity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一般市场计划量'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='market_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一般市场价格'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='market_sales_revenue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一般市场销售额'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='market_sales_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一般市场销售量'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='sales_personnel_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='销售人员数量'),
        ),
        migrations.AddField(
            model_name='marketindicator',
            name='theoretical_market_share',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='理论市场占有率'),
        ),
    ]
