# Generated by Django 5.0.7 on 2024-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_marketindicator_period_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_6',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='period_7',
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='accumulated_inventory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='累积产品库存'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='equipment_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设备生产能力'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='equipment_load',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生产设备负荷'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='market_output',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一般市场产量'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='personnel_load',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生产人员负荷'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='product_quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品质量评价'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='production_personnel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生产人员数量'),
        ),
        migrations.AddField(
            model_name='productionindicator',
            name='robot_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='机器人累计数'),
        ),
    ]
