# Generated by Django 5.0.7 on 2024-11-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_decisionevaluation_score_period_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationweight',
            name='round_id',
        ),
        migrations.RemoveField(
            model_name='financialindicator',
            name='round_id',
        ),
        migrations.RemoveField(
            model_name='marketindicator',
            name='round_id',
        ),
        migrations.RemoveField(
            model_name='productionindicator',
            name='round_id',
        ),
        migrations.DeleteModel(
            name='DecisionEvaluation',
        ),
        migrations.DeleteModel(
            name='EvaluationWeight',
        ),
        migrations.DeleteModel(
            name='FinancialIndicator',
        ),
        migrations.DeleteModel(
            name='MarketIndicator',
        ),
        migrations.DeleteModel(
            name='ProductionIndicator',
        ),
    ]
